---
- name: create scripts directory
  file:
    path: /opt/scripts
    state: directory
    mode: 0755

- name: create log directory
  become: yes
  file:
    path: /var/log/plot
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_effective_group_id }}"

- name: copy scripts
  template:
    src: "{{ item }}"
    dest: "{{ scripts.directory }}/{{ item }}"
    mode: 0755
  loop:
    - plot.sh
    - start_gui.sh

- name: copy plot service
  become: yes
  template:
    src: chia-plot.service
    dest: /etc/systemd/system/chia-plot.service

- name: ensure chia plot service is enabled and started
  become: yes
  systemd:
    name: chia-plot
    state: started
    enabled: yes
