---
- hosts: ploters
  gather_facts: yes

  vars:
    blockchain:
      directory: /opt/chia-blockchain
      version: latest
    plotter:
      directory: /opt/chia-plotter
      version: a9a49031ac03504b272b7199ef3e071c2d93e9cc
    scripts:
      directory: /opt/scripts

  pre_tasks:
    - name: create directories
      become: yes
      file:
        path: "{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_effective_group_id }}"
        state: directory
      loop:
        - "{{ blockchain.directory }}"
        - "{{ plotter.directory }}"
        - "{{ scripts.directory }}"
    - name: install tools
      become: yes
      apt:
        name:
          - curl
          - ansible
          - mdadm
        update_cache: yes

  roles:
    - role: dragomirr.git
      git_repo:
        - repo: https://github.com/Chia-Network/chia-blockchain
          dest: "{{ blockchain.directory }}"
          version: "{{ blockchain.version }}"
          force: yes
        - repo: https://github.com/madMAx43v3r/chia-plotter
          dest: "{{ plotter.directory }}"
          version: "{{ plotter.version }}"
      tags:
        - git
        - setup

    - role: blockchain
      tags: blockchain

    - role: plotter
      tags: plotter

    - role: scripts
      tags: scripts
